image: docker:latest

stages:
  - build
  - deploy

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

services:
  - name: docker:dind
    alias: docker_dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $TEST_IMAGE .
    - docker run -d -p 8080:80 $TEST_IMAGE
    - apk add --no-cache curl
    - chmod +x ./smoke-tests.sh
    - ./smoke-tests.sh
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE

deploy:
  stage: deploy
  script:
    - apk add --no-cache terraform
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - terraform init -from-module=manifests -var ssh_key_id=$SSH_KEY_ID -var token=$DO_TOKEN
    - terraform apply -auto-approve -var ssh_key_id=$SSH_KEY_ID -var token=$DO_TOKEN
