image: docker:latest

stages:
  - build

variables:
  TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

services:
  - name: docker:dind
    alias: docker_dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $TEST_IMAGE .
    - docker run -d -p 8080:80 $TEST_IMAGE
    - apk add --no-cache curl
    - chmod +x ./smoke-tests.sh
    - ./smoke-tests.sh
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
